### PR TITLE
Slow down repo refresh rate

### PR DESCRIPTION
**Pull request by vansivallab**
@jiffyclub

### CODE REVIEW

**Comment by gwax** [comment]
For production, should we go even slower?

**Comment by jiffyclub** [comment]
The downside of making this slower is that it makes it harder to ship fixes.

**Comment by vansivallab** [comment]
Id prefer like every 3 hours to be safe (cuz most dags take 1 hour or so). But merging fixes would take time. Im not sure what the right balance is.

**Comment by jiffyclub** [comment]
I wouldn't want this to go any slower than say 30-60 minutes without having a separate way to manually trigger code updates (I guess you can rebuild the server?). Also, we can let the the analytics repo update more frequently than the pipeline repo because it's not pulled from master. That way we can at least quickly apply fixes for ATL code.

**Comment by gwax** [comment]
You can also `aptible restart --app=airflow-pipeline` to manually trigger a refresh.

**Pull request merged**
